name: cubic_task
description: "Secure Banking Branch Locator - Flutter Technical Assessment"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  flutter_credit_card: ^4.1.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Network
  dio: ^5.7.0
  http: ^1.2.2

  # Local Storage & Encryption
  sqflite: ^2.3.3+2
  sqflite_sqlcipher: ^3.3.0
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2

  # Biometric Authentication
  local_auth: ^2.3.0

  # Maps & Location (Free - No API Key Required)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

  # Utilities
  connectivity_plus: ^6.1.0
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
